# PATHを/usr/local/binを優先にする
export PATH=/usr/local/bin:$PATH
# python
if [ -e $HOME/.pyenv ]; then
    export PYENV_ROOT=$HOME/.pyenv
    export PATH=$HOME/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    echo "pyenv started"
fi

# google app engineのSDKにパスを通す．
if [ -d $HOME/bin/go_appengine/ ]; then
    export PATH=$PATH:$HOME/bin/go_appengine/
fi

# vim: filetype=zsh
