#!/usr/bin/env bash

tmpfile=`mktemp`
trap "echo 'finished successfully'; rm -f $tmpfile; exit 0;" 0
trap "echo 'remove tempfile'; rm -f $tmpfile; exit 1;" 1 2 3 15

# define
ATOM_ROOT=$HOME/.atom
PACKAGES_FILE=packages.txt

# new packages check
apm list -bi > $tmpfile
diff $ATOM_ROOT/$PACKAGES_FILE $tmpfile | grep ">" | awk '{print $2}' > $tmpfile
echo "new packages"
echo "----------------"
echo "starting install ..."
apm install --packages $tmpfile
# download new packages
# apm install --packages-file $ATOM_ROOT/$PACKAGES_FILE
