# utils
[[plugins]]  # plugin manager
repo = 'Shougo/dein.vim'

# input support
[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]  # 括弧文字操作
repo = 'tpope/vim-surround'

[[plugins]]  # 文字整形
repo = 'junegunn/vim-easy-align'

[[plugins]]  # コメントアウト切り替え
repo =  'tyru/caw.vim'


# motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'


# visualization
[[plugins]]  # インデント可視化
repo = 'Yggdroot/indentLine'

[[plugins]] # color theme
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]] # statusラインを綺麗に表示
repo = 'itchyny/lightline.vim'


# editorconfig
[[plugins]]
repo = "editorconfig/editorconfig-vim"
