# unite
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_path = '.*'


# autocomplete
[[plugins]]
repo = 'Shougo/deoplete.vim'
on_i = 1
if = 'has("nvim")'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
if = 'has("lua")'

[[plugins]]
repo = 'Shougo/neocomplecache.vim'
on_i = 1
if = '!has("lua")'

# utils
[[plugins]]  # スニペット
repo = 'Shougo/neosnippet.vim'
on_path = '.*'

[[plugins]]  # スニペットソース
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet.vim']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_path = ".*"

[[plugins]]
repo = 'majutsushi/tagbar'
on_i = 1

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_path = ".*"


# motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
on_path = ".*"

[[plugins]]
repo = 'kana/vim-submode'
on_path = ".*"


# syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ["go"]

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ["go"]

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
if = 'has("nvim")'
    [plugins.build]
    unix = 'make'
    osx = 'make'

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
if = '!has("nvim")'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3']
if = 'has("nvim")'
