# unite
[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_path = '.*'


# utils
[[plugins]]  # スニペット
repo = 'Shougo/neosnippet.vim'
on_path = '.*'

[[plugins]]  # スニペットソース
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet.vim']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_path = ".*"


# motion
[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'kana/vim-submode'


# syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ["go"]

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ["go"]

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
    [plugins.build]
    unix = 'make'
    osx = 'make'

# python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'python3']
